apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:0.33.1
      ports:
      - name: http
        containerPort: 8181
      args:
      - "run"
      - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
      - "--server"
