apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    component: ci
spec:
  containers:
  - name: jnlp-slave
    image: openpolicyagent/opa
    ports:
      - containerPort: <Port>
