apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa
      ports:
      - name: http
        containerPort: 8181
    - name: terraform
      image: 'hashicorp/terraform:light'
      command:
        - sleep
        - '3600'
